[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Nicolás Vargas Ortega <nvortega92@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/*"]

[dependencies]
day1 = { path = "crates/day1" }